### ISSUE TITLE
Switch to `cursor_display_column`

### ISSUE THREAD

**Issue by FlyingWombat** [insipx/kak-crosshairs#14]
`cursor_display_column` was just added to Kakoune as a state variable.
See https://github.com/mawww/kakoune/issues/2788

**Comment by insipx** [comment]
Nice! This should make things much easier

**Comment by FlyingWombat** [comment]
Should we make the switch now, and have to use Kakoune at git master, or wait until the next release?

**Comment by insipx** [comment]
I think we should wait until the next Kakoune release. Personally I'm on kakoune master (because the fedora release was behind one or two releases last I checked), but I wouldn't want to screw up anybodies configuration by accident.

Maybe creating a `next` branch in this repo for the integration of newer features could be done. Not sure how that would integrate with kakoune's `plug` plugin, though. If users can specify branches using `plug` than it would be pretty easy to switch between versions of `kakoune-crosshairs`.

**Comment by FlyingWombat** [comment]
> Maybe creating a `next` branch 

It seems a lot of plugins have been doing that: where `master` targets the latest release of Kakoune, and `next` targets Kakoune's git master.

**Comment by eikenb** [comment]
cursor_display_column was included in the v2019.07.01 release
